// Generated by Apple Swift version 2.3 (swiftlang-800.10.12 clang-800.0.38)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if defined(__has_include) && __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
# if defined(__has_feature) && __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if defined(__has_feature) && __has_feature(modules)
@import ObjectiveC;
@import UIKit;
#endif

#import <LPMobileSDK/LPMobileSDK.h>

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
@protocol LPMobileSDKDelegate;
@class LIOLookIOManager;
@class NSURL;
@class UIWindow;

SWIFT_CLASS("_TtC11LPMobileSDK13DelegateProxy")
@interface DelegateProxy : NSObject <LIOLookIOManagerDelegate>
@property (nonatomic, strong) id <LPMobileSDKDelegate> _Null_unspecified delegate;
- (void)lookIOManager:(LIOLookIOManager * _Null_unspecified)aManager onEvent:(NSString * _Null_unspecified)eventName withParameters:(NSDictionary * _Null_unspecified)parameters;
- (void)lookIOManager:(LIOLookIOManager * _Null_unspecified)aManager didUpdateEnabledStatus:(BOOL)lookioIsEnabled;
- (void)lookioManager:(LIOLookIOManager * _Null_unspecified)manager didChangeEnabled:(BOOL)enabled forSkill:(NSString * _Null_unspecified)skill forAccount:(NSString * _Null_unspecified)account;
- (void)lookIOManagerDidHideControlButton:(LIOLookIOManager * _Null_unspecified)aManager;
- (void)lookIOManagerDidShowControlButton:(LIOLookIOManager * _Null_unspecified)aManager;
- (void)lookIOManagerDidShowChat:(LIOLookIOManager * _Null_unspecified)aManager;
- (void)lookIOManagerDidHideChat:(LIOLookIOManager * _Null_unspecified)aManager;
- (void)lookIOManagerDidEndChat:(LIOLookIOManager * _Null_unspecified)aManager;
- (void)lookIOManager:(LIOLookIOManager * _Null_unspecified)aManager didSendNotification:(NSString * _Null_unspecified)notification withUnreadMessagesCount:(NSInteger)count;
- (id _Null_unspecified)lookIOManager:(LIOLookIOManager * _Null_unspecified)aManager linkViewForURL:(NSURL * _Null_unspecified)aURL;
- (uint32_t)lookIOManagerEnabledCollaborationComponents:(LIOLookIOManager * _Null_unspecified)aManager;
- (BOOL)lookIOManagerShouldUseCustomActionForChatNotAnswered:(LIOLookIOManager * _Null_unspecified)aManager;
- (void)lookIOManagerCustomActionForChatNotAnswered:(LIOLookIOManager * _Null_unspecified)aManager;
- (BOOL)lookIOManagerShouldCacheChatMessagesForReconnect:(LIOLookIOManager * _Null_unspecified)aManager;
- (BOOL)lookIOManagerShouldReportCallDeflection:(LIOLookIOManager * _Null_unspecified)aManager;
- (BOOL)lookIOManagerSingleSignOnEnabled:(LIOLookIOManager * _Null_unspecified)aManager;
- (NSURL * _Null_unspecified)lookIOManagerSingleSignOnKeyGenURL:(LIOLookIOManager * _Null_unspecified)aManager;
- (UIWindow * _Null_unspecified)lookIOManagerMainWindowForHostApp:(LIOLookIOManager * _Null_unspecified)aManager;
- (BOOL)lookIOManager:(LIOLookIOManager * _Null_unspecified)aManager shouldRotateToInterfaceOrientation:(UIInterfaceOrientation)anOrientation;
- (BOOL)lookIOManagerShouldAutorotate:(LIOLookIOManager * _Null_unspecified)aManager;
- (NSInteger)lookIOManagerSupportedInterfaceOrientations:(LIOLookIOManager * _Null_unspecified)aManager;
- (BOOL)supportDeprecatedXcodeVersions;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11LPMobileSDK11LPMobileSDK")
@interface LPMobileSDK : LIOLookIOManager
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithWindow:(UIWindow * _Nullable)window delegate:(id <LIOLookIOManagerDelegate> _Nullable)delegate;
+ (void)initiateLPMobileSDK:(UIWindow * _Nullable)window delegate:(id <LIOLookIOManagerDelegate> _Nullable)delegate;
+ (void)setSDKDelegate:(id <LIOLookIOManagerDelegate> _Nullable)delegate;
@end


SWIFT_PROTOCOL("_TtP11LPMobileSDK19LPMobileSDKDelegate_")
@protocol LPMobileSDKDelegate <LIOLookIOManagerDelegate>
@optional
- (void)lpmobileSDKManager:(LPMobileSDK * _Null_unspecified)aManager onEvent:(NSString * _Null_unspecified)eventName withParameters:(NSDictionary * _Null_unspecified)parameters;
- (void)lpmobileSDKManager:(LPMobileSDK * _Null_unspecified)aManager didUpdateEnabledStatus:(BOOL)lookioIsEnabled;
- (void)lpmobileSDKManager:(LPMobileSDK * _Null_unspecified)aManager didChangeEnabled:(BOOL)enabled forSkill:(NSString * _Null_unspecified)skill forAccount:(NSString * _Null_unspecified)account;
- (void)lpmobileSDKManagerDidHideControlButton:(LPMobileSDK * _Null_unspecified)aManager;
- (void)lpmobileSDKManagerDidShowControlButton:(LPMobileSDK * _Null_unspecified)aManager;
- (void)lpmobileSDKManagerDidShowChat:(LPMobileSDK * _Null_unspecified)aManager;
- (void)lpmobileSDKManagerDidHideChat:(LPMobileSDK * _Null_unspecified)aManager;
- (void)lpmobileSDKManagerDidEndChat:(LPMobileSDK * _Null_unspecified)aManager;
- (void)lpmobileSDKManager:(LPMobileSDK * _Null_unspecified)aManager didSendNotification:(NSString * _Null_unspecified)notification withUnreadMessagesCount:(NSInteger)count;
- (id _Null_unspecified)lpmobileSDKManager:(LPMobileSDK * _Null_unspecified)aManager linkViewForURL:(NSURL * _Null_unspecified)aURL;
- (uint32_t)lpmobileSDKManagerEnabledCollaborationComponents:(LPMobileSDK * _Null_unspecified)aManager;
- (BOOL)lpmobileSDKManagerShouldUseCustomActionForChatNotAnswered:(LPMobileSDK * _Null_unspecified)aManager;
- (void)lpmobileSDKManagerCustomActionForChatNotAnswered:(LPMobileSDK * _Null_unspecified)aManager;
- (BOOL)lpmobileSDKManagerShouldCacheChatMessagesForReconnect:(LPMobileSDK * _Null_unspecified)aManager;
- (BOOL)lpmobileSDKManagerShouldReportCallDeflection:(LPMobileSDK * _Null_unspecified)aManager;
- (BOOL)lpmobileSDKManagerSingleSignOnEnabled:(LPMobileSDK * _Null_unspecified)aManager;
- (NSURL * _Null_unspecified)lpmobileSDKManagerSingleSignOnKeyGenURL:(LPMobileSDK * _Null_unspecified)aManager;
- (UIWindow * _Null_unspecified)lpmobileSDKManagerMainWindowForHostApp:(LPMobileSDK * _Null_unspecified)aManager;
- (BOOL)lpmobileSDKManager:(LPMobileSDK * _Null_unspecified)aManager shouldRotateToInterfaceOrientation:(UIInterfaceOrientation)anOrientation;
- (BOOL)lpmobileSDKManagerShouldAutorotate:(LPMobileSDK * _Null_unspecified)aManager;
- (NSInteger)lpmobileSDKManagerSupportedInterfaceOrientations:(LPMobileSDK * _Null_unspecified)aManager;
- (BOOL)lpmobileSDKManagerSupportDeprecatedXcodeVersions;
@end

#pragma clang diagnostic pop
